//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kayno.AI.Studio.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kayno.AI.Studio.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Save current payload parameters? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Dialog_ComfirmPresetSave {
            get {
                return ResourceManager.GetString("Dialog_ComfirmPresetSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please Select stable diffusion output dir に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Dialog_DefineSDOutputPath {
            get {
                return ResourceManager.GetString("Dialog_DefineSDOutputPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please Select stable diffusion dir に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Dialog_DefineSDPath {
            get {
                return ResourceManager.GetString("Dialog_DefineSDPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   over 1000 files detected. Are you sure to Procced?? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Dialog_ImageGallery_Over1000 {
            get {
                return ResourceManager.GetString("Dialog_ImageGallery_Over1000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Starting Initializing Process. This will take a while. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Dialog_InitialLaunch {
            get {
                return ResourceManager.GetString("Dialog_InitialLaunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure to reset models list? (also reset current parameters) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Dialog_ResetModelsConfirm {
            get {
                return ResourceManager.GetString("Dialog_ResetModelsConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ✦ Generate に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Dock_Gen_Do {
            get {
                return ResourceManager.GetString("Dock_Gen_Do", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Send to WebUI に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Dock_Gen_SendDataOnly {
            get {
                return ResourceManager.GetString("Dock_Gen_SendDataOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ┼  Set Region に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Dock_ScreenCapture_Region {
            get {
                return ResourceManager.GetString("Dock_ScreenCapture_Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FullScreen に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ImageGallery_Fullscreen {
            get {
                return ResourceManager.GetString("ImageGallery_Fullscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reload Images に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ImageGallery_Reload {
            get {
                return ResourceManager.GetString("ImageGallery_Reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reload Models or others. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Pane_ButtonReload {
            get {
                return ResourceManager.GetString("Pane_ButtonReload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open App Settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Pane_ButtonSettings {
            get {
                return ResourceManager.GetString("Pane_ButtonSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Toggle Panel. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Pane_ButtonToggleVisible {
            get {
                return ResourceManager.GetString("Pane_ButtonToggleVisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select Preset Folder (only in Data) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PresetSlotManager_InitialMessage {
            get {
                return ResourceManager.GetString("PresetSlotManager_InitialMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Re-define screencapture region? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ScreenCapture_ConfirmDialog_Msg {
            get {
                return ResourceManager.GetString("ScreenCapture_ConfirmDialog_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Drag to Define Capture Region. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ScreenCaptureWindowMsg {
            get {
                return ResourceManager.GetString("ScreenCaptureWindowMsg", resourceCulture);
            }
        }
    }
}
